version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=serafim
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=apisolid
